Resources:
  RootBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "PublicRead"
      BucketName: "ben.axnick.com.au"
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "404.html"
  WWWBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "PublicRead"
      BucketName: "axnick.com.au"
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RootBucket
  Distribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - "ben.axnick.com.au"
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/index.html"
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: "none"
          TargetOriginId: "root"
          ViewerProtocolPolicy: "redirect-to-https"
        DefaultRootObject: "/index.html"
        Enabled: true
        HttpVersion: "http2"
        Origins:
          - Id: "root"
            DomainName: !GetAtt RootBucket.DomainName
            S3OriginConfig: {}
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:ap-southeast-2:702788515874:certificate/1861ca33-8762-48ba-8270-89f381c28968"
          SslSupportMethod: "sni-only"
