Resources:
  RootBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "BucketOwnerFullControl"
      BucketName: "pickaxe-me"
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "404.html"
  WWWBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "BucketOwnerFullControl"
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RootBucket
  Distribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - "pickaxe.me"
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/index.html"
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: "none"
          TargetOriginId: "root"
          ViewerProtocolPolicy: "redirect-to-https"
        Enabled: true
        HttpVersion: "http2"
        Origins:
          - Id: "root"
            DomainName: !GetAtt RootBucket.DomainName
            S3OriginConfig: {}
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:702788515874:certificate/9e03b53e-40e5-45c1-853c-01636042c2ad"
          SslSupportMethod: "sni-only"
  RootDnsRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneName: "pickaxe.me."
      Name: "pickaxe.me"
      Type: "A"
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: "Z2FDTNDATAQYW2" # Hardcoded for CloudFront
  WWWDnsRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneName: "pickaxe.me."
      Name: "www.pickaxe.me"
      Type: "CNAME"
      TTL: 60
      ResourceRecords:
        - !GetAtt WWWBucket.DomainName
