Resources:
  RootBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "PublicRead"
      BucketName: "ben.axnick.com.au"
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "404.html"
  WWWBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "PublicRead"
      BucketName: "www.axnick.com.au"
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref RootBucket
  Distribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - "ben.axnick.com.au"
          - "www.axnick.com.au"
          - "axnick.com.au"
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: "/index.html"
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: "none"
          TargetOriginId: "root"
          ViewerProtocolPolicy: "redirect-to-https"
        DefaultRootObject: "/index.html"
        Enabled: true
        HttpVersion: "http2"
        Origins:
          - Id: "root"
            DomainName: !GetAtt RootBucket.RegionalDomainName
            S3OriginConfig: {}
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:702788515874:certificate/b4ae9768-266d-410e-8c91-3fa49a15650c"
          SslSupportMethod: "sni-only"
